fail_fast: false
default_stages:
  - commit
repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args:
          - --profile=black

  - repo: https://github.com/psf/black
    rev: 23.9.0
    hooks:
      - id: black
        args:
          - --config=pyproject.toml

  - repo: https://github.com/myint/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        exclude: .*/__init__.py
        args:
          - --in-place
          - --remove-all-unused-imports
          - --expand-star-imports
          - --remove-duplicate-keys
          - --remove-unused-variables

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.4
    hooks:
      - id: autopep8
        args:
          - -i
          - -vvv

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-use-type-annotations
      - id: python-check-blanket-noqa

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.287'
    hooks:
      - id: ruff
        args:
          - --config
          - ./pyproject.toml
          - --fix

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        types:
          - python
        args:
          - -c
          - pyproject.toml
        additional_dependencies:
          - toml

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.0
    hooks:
      - id: mypy

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-symlinks
      - id: check-toml
      - id: debug-statements
      - id: no-commit-to-branch
        args:
          - --branch
          - main


#  - repo: https://github.com/python-poetry/poetry
#    rev: '1.5.0'
#    hooks:
#      - id: poetry-check
#      - id: poetry-lock
#        args:
#          - --no-update
