name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


permissions:
  checks: write


jobs:
  check:
    name: Pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3.1.0

      - name: Pre-commit checks
        uses: pre-commit/action@v3.0.0
        env:
          SKIP: no-commit-to-branch

  test:
    name: Tests
    runs-on: ubuntu-latest
    outputs:
      build-id: ${{ steps.generate-build-id.outputs.build-id }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3.1.0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: cache poetry install
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-1.1.12-0

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.4.0
          virtualenvs-create: true
          virtualenvs-in-project: false
          installer-parallel: true


      - name: cache deps
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: .venv
          key: pydeps-${{ hashFiles('**/poetry.lock') }}

          # Install dependencies. `--no-root` means "install all dependencies but not the project
          # itself", which is what you want to avoid caching _your_ code. The `if` statement
          # ensures this only runs on a cache miss.
      - run: poetry install --no-interaction --no-root
        if: steps.cache-deps.outputs.cache-hit != 'true'
      - run: poetry install --no-interaction
      - name: test
        run: |
          poetry run pytest --cov=pydiction --cov-report=xml:coverage.xml --junitxml=test-results/test-results.xml tests


      - name: Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: '**/test-results/*.xml'



      - name: Coverage Report
        uses: 5monkeys/cobertura-action@master
        if: success() || failure()
        with:
          path: coverage.xml
          minimum_coverage: 75
          fail_below_threshold: true


      - name: build
        run: |
          poetry build
